### ISSUE TITLE
Missing 'model' folder

### ISSUE THREAD

**Issue by bnapora** [maubreville/MITOS_WSI_CMC#1]
Repo appears to be missing the 'model' folder.  I copied from the CCMCT repo, and seems to work fine, but wanted to let you know its not in this one.

**Comment by maubreville** [comment]
Thanks so much! I will add it asap!

**Comment by bnapora** [comment]
No problem.  Not sure if you have time to help me on this, but thought I'd ask.  

I've been attempting to duplicate your findings on the TUPAC dataset.  Can you share the the notebooks you used for running the TL on AMIDA-train and subsequent inference/validation to determine F-score?

**Comment by maubreville** [comment]
I added the folder now.
