### ISSUE TITLE
Pre-trained models?

### ISSUE THREAD

**Issue by kesinger** [maubreville/MITOS_WSI_CMC#2]
Would it be possible to put some pre-trained models up somewhere?

**Comment by maubreville** [comment]
Certainly! Do you know any place where that's easily possible? github has some limitations and github-lfs is costly (We ran into limits of the free version frequently)

**Comment by kesinger** [comment]
Google drive?

**Comment by maubreville** [comment]
Sure! Is it sufficient to only provide you with the CODAEL-trained model?

**Comment by kesinger** [comment]
That'd be great! Thanks!

**Comment by maubreville** [comment]
There you go. Should be available for you now. Let me know should you run into problems.
