### ISSUE TITLE
MITOS_WSI_CMC_CODAEL_TR.sqlite is not in databases/

### ISSUE THREAD

**Issue by schwanabc** [maubreville/MITOS_WSI_CMC#3]
In RetinaNet-CMC-CODAEL.ipynb, MITOS_WSI_CMC_CODAEL_TR.sqlite is required to access the annotation. However, the file is not in the folder databases/. Can I use MITOS_WSI_CMC_CODAEL_TR_ROI instead?

**Comment by maubreville** [comment]
Yes, you can! The only difference is that the database also contains the Regions of Interest (ROI) for the mitotic count.  I will also upload the other file, however. Thanks for pointing out!

**Comment by maubreville** [comment]
Commit 1bd0befe7372326c5c516789a5652a6e4ffb1286 solves the issue.
